name: Deploy to EC2

on:
  push:
    branches:
      - aws-saved

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key and known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ec2-16-171-93-79.eu-north-1.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: SSH into EC2 and deploy
      run: |
        ssh -i ~/.ssh/id_rsa ubuntu@ec2-16-171-93-79.eu-north-1.compute.amazonaws.com "./build.sh"

    - name: Notify on failure
      if: failure()
      run: |
        echo "Deployment failed. Please check the workflow logs for details."
